spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3307/house_batch
    username: house
    password: house
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  batch:
    jdbc:
      initialize-schema: always
external:
  apartment-api:
    path: http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade
    service-key: jL5odMUdVM%2Fqtlz2MUo%2BzamxiA5mYwjcJmX1G8Q9XsNDbf5XdftChVKAt%2FXj4D3UvaqgRjWD8dAIkmQp4F%2F0pA%3D%3D


---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2